Add force_backup command line argument

diff --git a/backup_mc_daily b/backup_mc_daily
--- a/backup_mc_daily
+++ b/backup_mc_daily
@@ -31,33 +31,21 @@ eval $(parse_yaml /home/mcserver/minecraft/mc_backup/config.yml)
 
 script_start_time=$(date +"%Y-%m-%d %H:%M:%S")
 
+force_backup="False"
+
+while getopts ":f" opt; do
+    case $opt in
+        f)
+            force_backup="True"
+            ;;
+        \?)
+            echo "Invalid option: -$OPTARG" >&2
+            ;;
+    esac
+done
+
 # Change the directory to the log folder
 cd "$CONSTANTS_LOG_PATH"
-
-# Initialize an associative array to store player names and their occurrence count
-declare -A player_counts
-
-# Loop through each .gz file in the logs directory
-for file in *.gz; do
-    # Use zgrep to search for player names and extract them
-    names_found=$(zgrep -oE '[[:alnum:]_]+ joined the game' "$file" | awk '{print $1}')
-    
-    # Increment the occurrence count of each player name in the associative array
-    for name in $names_found; do
-        ((player_counts["$name"]++))
-    done
-done
-
-# Initialize an empty array to store player names that meet the minimum play requirement
-search_strings=()
-
-# Loop through the associative array and filter player names based on the minimum_play count
-for name in "${!player_counts[@]}"; do
-    count="${player_counts[$name]}"
-    if ((count >= PREFS_MINIMUM_PLAYS)); then
-        search_strings+=("$name")
-    fi
-done
 
 # Initialize variables to store the most recent file and date
 most_recent_file=""
@@ -77,50 +65,78 @@ find_world_paths() {
     done < <(find "$CONSTANTS_MINECRAFT_PATH" -maxdepth 1 -type d -name "world*" -print0)
 }
 
-# Search for each search string (player name) in the log files and determine the date of the most recent file containing a player name
-for search_string in "${search_strings[@]}"; do
-    # Use find to search for .log files and .gz files containing the current search string
-    # and compare their dates to find the most recent log file that includes one of the player names.
-    while IFS= read -r file; do
-        if [[ "$file" == *.gz ]]; then
-            # For .gz files, use zgrep
-            if zgrep -q "$search_string" "$file"; then
-                # Get the date of the file
-                file_date=$(get_file_date "$file")
-                # Compare the date of the current file with the most_recent_date
-                if [[ "$file_date" > "$most_recent_date" ]]; then
-                    most_recent_file="$file"
-                    most_recent_date="$file_date"
-                fi
-            fi
-        else
-            # For uncompressed .log files, use grep
-            if grep -q "$search_string" "$file"; then
-                # Get the date of the file
-                file_date=$(get_file_date "$file")
-                # Compare the date of the current file with the most_recent_date
-                if [[ "$file_date" > "$most_recent_date" ]]; then
-                    most_recent_file="$file"
-                    most_recent_date="$file_date"
-                fi
-            fi
-        fi
-    done < <(find "$CONSTANTS_LOG_PATH" -type f \( -name "*.log" -o -name "*.gz" \))
-done
+if [[ "$force_backup" == "False" ]]; then
+    # Initialize an associative array to store player names and their occurrence count
+    declare -A player_counts
 
-# Check if the most recent backup is earlier or later than the most recent log file containing a player name
-if [[ "$most_recent_date" != "0000-00-00" ]]; then
-    # Check if any files in the backup folder are newer than the most recent date
-    if [[ $(find "$CONSTANTS_BACKUP_PATH" -type f -name "*.gz" -newermt "$most_recent_date" 2>/dev/null) ]]; then
-        result="True: Some files in $CONSTANTS_BACKUP_PATH were created after $most_recent_date."
+    # Loop through each .gz file in the logs directory
+    for file in *.gz; do
+        # Use zgrep to search for player names and extract them
+        names_found=$(zgrep -oE '[[:alnum:]_]+ joined the game' "$file" | awk '{print $1}')
+        
+        # Increment the occurrence count of each player name in the associative array
+        for name in $names_found; do
+            ((player_counts["$name"]++))
+        done
+    done
+
+    # Initialize an empty array to store player names that meet the minimum play requirement
+    search_strings=()
+
+    # Loop through the associative array and filter player names based on the minimum_play count
+    for name in "${!player_counts[@]}"; do
+        count="${player_counts[$name]}"
+        if ((count >= PREFS_MINIMUM_PLAYS)); then
+            search_strings+=("$name")
+        fi
+    done
+
+    # Search for each search string (player name) in the log files and determine the date of the most recent file containing a player name
+    for search_string in "${search_strings[@]}"; do
+        # Use find to search for .log files and .gz files containing the current search string
+        # and compare their dates to find the most recent log file that includes one of the player names.
+        while IFS= read -r file; do
+            if [[ "$file" == *.gz ]]; then
+                # For .gz files, use zgrep
+                if zgrep -q "$search_string" "$file"; then
+                    # Get the date of the file
+                    file_date=$(get_file_date "$file")
+                    # Compare the date of the current file with the most_recent_date
+                    if [[ "$file_date" > "$most_recent_date" ]]; then
+                        most_recent_file="$file"
+                        most_recent_date="$file_date"
+                    fi
+                fi
+            else
+                # For uncompressed .log files, use grep
+                if grep -q "$search_string" "$file"; then
+                    # Get the date of the file
+                    file_date=$(get_file_date "$file")
+                    # Compare the date of the current file with the most_recent_date
+                    if [[ "$file_date" > "$most_recent_date" ]]; then
+                        most_recent_file="$file"
+                        most_recent_date="$file_date"
+                    fi
+                fi
+            fi
+        done < <(find "$CONSTANTS_LOG_PATH" -type f \( -name "*.log" -o -name "*.gz" \))
+    done
+
+    # Check if the most recent backup is earlier or later than the most recent log file containing a player name
+    if [[ "$most_recent_date" != "0000-00-00" ]]; then
+        # Check if any files in the backup folder are newer than the most recent date
+        if [[ $(find "$CONSTANTS_BACKUP_PATH" -type f -name "*.gz" -newermt "$most_recent_date" 2>/dev/null) ]]; then
+            result="True: Some files in $CONSTANTS_BACKUP_PATH were created after $most_recent_date."
+        else
+            result="False: No files in $CONSTANTS_BACKUP_PATH were created after $most_recent_date."
+        fi
     else
-        result="False: No files in $CONSTANTS_BACKUP_PATH were created after $most_recent_date."
+        result="None of the search strings found in any of the .log files."
     fi
-else
-    result="None of the search strings found in any of the .log files."
 fi
 
-if [[ $result == *"False"* ]]; then
+
+if [[ $result == *"False"* ] || [ $force_backup == "True"]]; then
     # Execute the backup.
     screen -R mc -xX stuff "say Server backup starting. World not saving until complete...$(printf '\r')"
     screen -R mc -xX stuff "save-off$(printf '\r')"
